unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g status-left-length 100
set -g status-style "fg=#6d7f8b"
set -g status-right "%D %I:%M%p"

set -g mouse on
set -g renumber-windows on
set -g history-limit 100000
